# Generated by Django 3.2.13 on 2022-04-20 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.CharField(max_length=5)),
                ('ticker_name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TxHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=160, unique=True)),
                ('tx_type', models.CharField(max_length=7)),
                ('previous_amount_from', models.FloatField(default=0)),
                ('previous_amount_to', models.FloatField(default=0)),
                ('current_amount', models.FloatField(default=0)),
                ('after_amount_from', models.FloatField(default=0)),
                ('after_amount_to', models.FloatField(default=0)),
                ('date_time', models.DateTimeField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_ticker', to='transactions.cointicker')),
                ('wallet_from', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wallet_f', to=settings.AUTH_USER_MODEL)),
                ('wallet_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='wallet_t', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateTimeField(auto_now_add=True)),
                ('last_up_date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('coin_ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbol', to='transactions.cointicker')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
