# Generated by Django 3.2.13 on 2022-04-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointicker',
            name='ticker_symbol',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
