# Generated by Django 3.2.13 on 2022-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_balance_txhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txhistory',
            name='tx_type',
            field=models.CharField(choices=[(1, 'AIRDROP-DEPOSIT'), (2, 'AIRDROP-SENT'), (3, 'BURN-SENT'), (4, 'BURN-DEPOSIT'), (5, 'P2P-SENT'), (6, 'P2P-DEPOSIT')], max_length=7),
        ),
    ]
