# Generated by Django 3.2.13 on 2022-04-20 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_txhistory_tx_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txhistory',
            name='tx_type',
            field=models.CharField(max_length=7),
        ),
    ]
